language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "TM33xEgDXgd+BfiZr48Vmci2OcfzDjk00p/Ehm222qSG/Asdj4xBk7nPHoyI5bAQEPX85DXIKrA7hlyyCfMNzpSlstnSBGEFrg+4ccRM29kCL5vcrn49oyo09aq/jmQD64c2cutw2AzfpI2fEoSSS4IKLz9BsUVGZD+GlaTqW8PBVfxwbpx7TDMEgXNfsngBXaJ5bcT7x3sWag1y7jfl9okWP/elZ/MIa5YSVzrv20ma7QGGcB/K21r+RVGkAGwXKqSM02JvI3qE1fDMkhYsa09dRKtxD1i321RCxfe3KRXJFBmr3xkCYALaLJsHQ03iHGlzXTj1SUYHgtS3yRWr3uf6+Weob+XQsGE8OY5BniTGOb79HUyviGs0eFDvETBackFS5a6rF7uTtWeEytG1tawLtQl6utnobFZYjzn+1YUESOFZqN1EbxuuxyO+TtwDrHdSJ4SM9zGNNrcR5sVngqfkEAT2xNmGt3m0DXgTR7LiXgLo0JfgnBZ9ucLiUC1rjyPsUhZRHuHyfDpRHwJMQOUAvB0iIGJmcRCQ+4Uy5hIuecGLn1Du4yTZAXzYBS9RxNTuXvLqjNvaWtR2dP9g9N0jzm3HE6bFi6fw9kEBAqBRo0ucVjTZDzOVdoe8JAs8fszqxqTmrA5xLOvg5bVOU4AE/JXwvO2EZFLDHYi9ljM="
branches:
  only:
  - master
